strivedi4u/hacktoberfest2025

- Subarray_with_given_Sum.cpp
I wrote cpp code as a solution to the problem
Subarray with given Sum
T.C -> O(N)
S.C->O(1)
> Add Subarray with given sum #3

- basic_calculator.py
added the code for basic calculator
> basic calculator#20

- Second largest element
it clearly tackle out with all the edge cases and is the correct optimized solution for this
so if their is any case that I didn't mentioned or is incorrect I would definitely change it 
thankyou
> Create Second largest element

- Search in Rotated Sorted Array.cpp
I have solved this problem.
Please merge it and add label of hacktoberfest accepted.
> Solved rotated sorted array

- MajorityElements.cpp
This PR introduces a new function majorityElement that identifies the majority element in an array. The function uses a hashmap to count occurrences of each element and returns the element that appears more than half the time. If no such element exists, it returns -1. This implementation is efficient and straightforward for finding majority elements in datasets.
> Add majorityElement function to find majority element in an array

- heightOfBinaryTree.cpp
I have created the solution of Height Of Binary Tree
The approach uses level order traversal (BFS) to find the height of a binary tree. It leverages a queue to traverse each level of the tree, starting from the root. At each level, the number of nodes is counted, and all child nodes are added to the queue. After processing all nodes at the current level, the height counter is incremented. This process continues until all levels are traversed, and the final value of the height counter gives the depth of the tree.
> Create Height of Binary Tree C++ File

- latest Calculator/index.html
- latest Calculator/script.js
- latest Calculator/styles.css
Hello Sir,
I have created a simple calculator using HTML, CSS, and JavaScript as my contribution to Hacktoberfest 2024. This is my first contribution as an open-source contributor. I kindly request your approval, as I learned Git and GitHub to make this contribution. I would be thrilled if you could label my submission with "Hacktoberfest Accepted," "Hacktoberfest 2024," "Hacktoberfest," and "Good Learner."
Thank you!
>  Latest Calculator

- floyd_warshall_algorithm.cpp
- kmp_string_matching.cpp
- kruskals_algorithm.cpp
- prims_algorithm.c
- tarjans_scc_algorithm.cpp
**Description**: This PR adds five essential algorithms that were previously no there in the repository:****
**1. Floyd-Warshall Algorithm:** Computes shortest paths between all pairs of vertices.
**2. Prim’s Algorithm:** Finds the minimum spanning tree for a connected weighted graph
**3. .KMP (Knuth-Morris-Pratt) Algorithm:** Efficient string matching algorithm
**4. .Kruskal's Algorithm**: Another method for finding the minimum spanning **tree.**
**5. Tarjan’s Algorithm:** Identifies strongly connected components in a directed graph.
> Added Floyd-Warshall, Prim’s, KMP, Kruskal’s, and Tarjan’s algorithms

- first_non_repeating_char_solved.cpp
Added optimal solution for majority element problem
C++ language used
Please approve the pr with "Hactoberfest" and required labels
> [ADD] added solution for first non repeating char problem

- majority_element_optimal_soln.cpp
- Added optimal solution for majority element problem 
- Time Complexity: O(N)
- Space Complexity: O(1)
- C++ language used
- Please approve the pr with "Hactoberfest" and required labels
> [ADD] added optimal solution of majority element problem

- Kruskal's_algorithm.cpp
I have successfully added Kruskals algorithm in ur project!, Please accept this as soon as possible :)
> Added Kruskals Algorithm

- kadanesAlgorithm.java
Feel free to merge the pull request as soon as possible.
> #HactoberFest2024

- .gitmodules
Jarvis is a voice-activated virtual assistant designed to perform tasks such as web browsing, playing music, fetching news, and responding to user queries using OpenAI's GPT-3.5-turbo model.
> Jarvis-AI-assistant

- Lexical-Analyzer.c
Implemented Lexical Analyzer in C programming language.
> Implemented Lexical-Analyzer in C

- tower_of_hanoi.java
This Java program solves the Tower of Hanoi puzzle, a classic problem in computer science and mathematics. It uses a recursive algorithm implemented in the solveTowerOfHanoi method to determine the sequence of moves needed to transfer a stack of disks from one peg to another, following the puzzle's rules. </br> The program is interactive, prompting users to input the number of disks they want to solve, making it flexible for various puzzle sizes. It then outputs a step-by-step solution, showing each disk movement between the three towers (A, B, and C). This implementation showcases key programming concepts such as recursion, user input handling, and algorithmic problem-solving, serving as an excellent example for understanding both the Tower of Hanoi problem and recursive programming …
> Interactive Tower of Hanoi Solver in Java

- Smart Study Management System/Code.py
- Smart Study Management System/details.md
I have added the code for Smart Study Management System in python.
> Added Smart Management System

- rotated_sorted_array/rotated_sorted_array.cpp
@strivedi4u sir  , rotated sorted array question is solved by using recursion the most efficient and easiest way
> rotated_sorted_array

- MorrisInorderTraversal.cpp
It adds the code for morris inorder traversal which traverses the tree in O(1) time complexity
> added morris traversal inorder code

- age-calculator/app.py
- age-calculator/readme.md
- age-calculator/static/styles.css
- age-calculator/templates/index.html
hi, i just added a feature (age - calculator)
@trivedi4u  Please check it
> feat (age-calculator) : new feature age calculator is added 

- AngramsString.cpp
create frequency arrays to track character counts for both the pattern and a sliding window in the string, slide the window across the string while updating these counts, and record the starting indices whenever the window's frequency matches the pattern's, returning all such indices.
> Find All Anagrams in String Using C++

- sun_earth_moon.html
sun, earth and moon system created using html
> solar system model using html

- Algorithm.java
A* (A-star) is an efficient pathfinding algorithm used to find the shortest path between nodes in a weighted graph. It uses two main functions: g(n) (the cost to reach the current node) and h(n) (a heuristic estimate of the cost to reach the goal). A* combines these to minimize the function f(n) = g(n) + h(n), expanding nodes with the lowest f(n) value first. It is widely used in navigation systems, games, and AI, as it guarantees finding the shortest path when the heuristic is admissible
> Create Algorithm for Optimal Search.java

- KadanesAlgoCpp.cpp
The provided code implements a function to find the maximum subarray sum using Kadane's Algorithm in C++. This algorithm efficiently calculates the maximum sum of a contiguous subarray by iterating through the input array only once. It maintains two variables: res to store the maximum sum found so far and currSum to track the current subarray's sum. As it iterates through the array, currSum is updated by adding the current element. If currSum exceeds res, it updates res. If currSum falls below zero, it is reset to zero, effectively starting a new subarray. This approach ensures optimal performance with a time complexity of O(n).
> Implemented the Kandanes Algorithm

- portfolio.html
*Added portfolio.html file
*Please use label 'hacktoberfest-accepted' label.
> Curated portfolio.html

- python/Tuples.py
Hello Guys, I worked on Implementing  **input validation** for the user only to allow positive numbers, Lets Discuss Further if there  is something I need to change
> Tuples Error Handling

- DFS.cpp
Add .cpp extensions to source code files for proper compilation and file organization
> Add .cpp extensions to DFS soruce file

- Container With Most Water/solution.py
So here is the solution for an important problem "container with most water"
issue #123 
Thank you @strivedi4u
> To Add solution for container with most water

- Spiral matrix problem
The Spiral Matrix problem is an intriguing exercise in data structure and algorithm design. The goal is to fill an [n x n] matrix in a spiral order, starting from the top-left corner and continuing in a clockwise direction until the entire matrix is filled. This requires careful manipulation of row and column indices, and keen attention to boundary conditions, as the indices must be adjusted after completing each side of the spiral.
The typical approach involves maintaining four boundaries—top, bottom, left, and right. You traverse the matrix in four steps: from left to right, top to bottom, right to left, and bottom to top, progressively tightening these boundaries to avoid re-processing cells. This process continues until all elements are covered.
Implementing the Spiral Matrix problem …
> Added spriral matrix problem in DSA

- N_Queen.cpp
- Valid_Paranthesis.cpp
Solve the Valid paranthesis Problem using the optimized solution.
> adding the Valid paranthesis Problem #106

- App.css
- App.js
Adding react code of expense tracker
> Expense Tracker

- Hotel Management System.py
I have designed Hotel Management System in python. It is designed to manage room bookings. It provides a console-based interface for checking room availability, booking rooms, viewing current bookings, and handling checkouts. The program uses a dictionary to store room numbers and customer details, making it easy to track which rooms are occupied or vacant. This system is suitable for small hotels or as a learning project for implementing basic booking functionality. It would be grateful if you merge it.
Thank You!
> Create Hotel Management System.py

- python/Contains Duplicate.py
- python/Missing Number.py
- python/Palindrome Number.py
- python/TwoSum.py
solve issue :#63
Added the following code to the folder 'Python'
1.Contains Duplicate
2.Missing Number
3.Palindrome Number
4.TwoSum
> Python problems -

- Peak Index in a Mountain Array.cpp
- aggressive_cow.cpp
- panagrap.cpp
- sqrt(x).cpp
Added some of the most important arrays Interview questions asked in FAANG
> Arrays Interview questions 

- Armstrong.c
This .c file contains the code to prove if a number is an armstrong number or not in C language. Armstrong number is a number whose digits when extracted, raised to the power of the number of digits and added together give the same number.
> Added Armstrong.c File

- ‎Data-Structures-and-Algorithms-for-Interviews/N-Queens Problem.cpp
Hey @strivedi4u, I have added the code for N-Queens Problem using a backtracking approach in C++. The implementation includes a detailed explanation of the concept.
I kindly request that you merge this PR as part of Hacktoberfest 2024. Looking forward to your feedback and contributing further!
> Added N-Queens Problem code  in C++

- Hacktoberfest-Tracker/index.html
- Hacktoberfest-Tracker/script.js
- Hacktoberfest-Tracker/style.css
🚀 Overview
This pull request introduces a comprehensive HacktoberFest 2025 Tracker that helps contributors track and manage their progress efficiently.
🧭 Key Features
🧩 Enhanced Statistics Dashboard
Displays total contributions and individual counters for Merged, Approved, Pending PRs
Live updating stats for real-time progress tracking
📝 Advanced Contribution Form
Added PR URL field (optional)
Notes/Description input for each contribution
Dropdowns for Programming Language and Contribution Type (Bug Fix, Feature, Documentation, etc.)
🔍 Search & Filter System
Real-time search for finding contributions quickly
Filter buttons for status: All, Pending, Approved, Merged, Rejected
Search includes repo names, PR numbers, notes, and languages
✏️ Edit Functionality
Introduced Edit button for …
> Create HacktoberFest 2025 Tracker with Enhanced UI and Advanced Features

- RegularExpressionMatching.java
Related Issue  #462
🧠Problem Description
Implement the Regular Expression Matching algorithm that determines whether a given string s matches a pattern p which includes the special characters:
. → matches any single character
→ matches zero or more occurrences of the preceding element
The solution must return true if the input string matches the pattern, otherwise false.
💡 Intuition
A direct recursive approach to this problem would repeatedly evaluate the same subproblems.
To optimize, we use Dynamic Programming (DP) to store intermediate results.
We define:
dp[i][j] = true if the first i characters of s match the first j characters of p.
Then, using transitions:
When p[j-1] is a regular character or .,
→ dp[i][j] = dp[i-1][j-1]
When p[j-1] == '*', it can represent:
Zero occurrences → …
> Add “Regular Expression Matching” (DP)

- Software Engineering/software-architecture.md
- Software Engineering/software-metrics.md
- Software Engineering/software-security.md
- Software Engineering/software-testing.md
This PR introduces a comprehensive set of topics to help candidates prepare for software engineering interviews.
**Added Topics:**
1. Software Architecture
2. Software Metrics
3. Software Security
4. Software Testing
> Software Engineering Interview Preparation

- simple_calculator.py
Added a simple calculator program in Python under `python/simple_calculator.py`.
Beginner-friendly program that demonstrates arithmetic operations using if/else statements.
- Supports +, -, *, /
- Handles division by zero
> feat(python): add simple calculator program

- Backtraking/CountNumbersWithUniqueDigits.java
- Backtraking/wordBreak2.java
Implemented Count Numbers with Unique Digits (Leetcode 357) in Java using combinatorial approach to count numbers with unique digits up to 10^n in 
/backtracking/CountNumbersWithUniqueDigits.java
> Added Java solution for Count Numbers with Unique Digits using combinatorics

- MinCostMaxFlow.java
feat: Add Java implementation for Min-Cost Max-Flow (MCMF) using Successive Shortest Path (SSP)
> Create  MinCostMaxFlow.java

- TarjanBridgesArticulation.java
This PR introduces a fully documented Java implementation of Tarjan’s Algorithm to detect Bridges and Articulation Points in an undirected graph.
Highlights:
📌 Detects critical edges (bridges) whose removal increases connected components.
📌 Identifies articulation points (cut vertices) that are crucial for graph connectivity.
📝 Code includes step-by-step inline documentation and an example graph with output.
⏱️ Efficient O(V + E) time complexity.
Why this is important:
Essential in system design & networking to identify weak links in a network.
Frequently asked in advanced coding interviews.
Complements existing graph algorithms (Dijkstra, Kruskal, Tarjan’s SCC) already in the repo.
Sample Output (from included example):
🔗 Bridges in the Graph:
Bridge found: (3 - 4)
Bridge found: (1 - 3) …
> Added Tarjan Bridges Articulation code

- Array and linked list in C++/arraydeletion.cpp
- Array and linked list in C++/arrayinsertion.cpp
- Array and linked list in C++/arraymaxmin.cpp
- Array and linked list in C++/arrayreversal.cpp
- Array and linked list in C++/linkedlist.cpp
- Array and linked list in C++/linklistdelete.cpp
- Array and linked list in C++/linklistdynentry.cpp
- Array and linked list in C++/linklistinsert.cpp
- Array and linked list in C++/move0toendarray.cpp
- Array and linked list in C++/removeduplicateelementsarray.cpp
I added a few programs on arrays and linked lists, using C++.
> Array and linked list added

- text_utils.py
This module provides various utility functions for text processing, including palindrome checking, word counting, character frequency analysis, string reversal, and unique word extraction.
> Add text utility functions for string processing

- #14 BFS
- Replaced raw array with vector<int> for visited tracking (safer & more scalable)
- Used range-based for loops for cleaner iteration
- Fixed graph size mismatch (V = 6 instead of 5)
- Simplified output printing with range-for
- Added note for handling directed vs. undirected edges
- Improved code readability and maintainability
> Update #14: Optimize BFS implementation

- hacktoberfest2025.html
This PR adds an example of Image Mapping in HTML.
- Created a file `image-mapping.html` inside the web/ folder.
- Added a world flags background image with clickable mapped areas (India, USA, Japan).
- Each mapped region opens the respective Wikipedia page in a new tab.
- Styled the page with simple CSS for better readability.
- This project demonstrates the basics of HTML <map> and <area> usage in a beginner-friendly way.
This contribution is part of Hacktoberfest 2025 🎉
>  hacktoberfest2025.html

- ReverseArray.py
This PR adds a Python solution to reverse an array
✅ Problem: Reverse Array
✅ Language: Python
✅ Clean and readable code
✅ Beginner-friendly
Kindly add the Hacktoberfest-accepted label.
Thank you for maintaining this awesome repository!
> Add Reverse Array solution in Python

- animation.html
Added a new file animation.html with a modern animated loader using HTML and CSS.
The animation demonstrates creative use of keyframes and flexbox for visual effect.
🍉🍉🍉🍉🍉🍉
> added animation webpage

- Regular-expression-matching.py
When a star is present, we may need to check many different suffixes of the text and see if they match the rest of the pattern. A recursive solution is a straightforward way to represent this relationship.
> Regular-expression-matching.py
